# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: mypcagent

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'sample'
    publishLocation: 'Container'

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'Azuresonar'
    scannerMode: 'Other'

- task: TomcatDeployment@1
  inputs:
    TomcatUrl: 'http://192.168.126.131:8081/'
    Username: 'tomcat'
    Password: 'tomcat'
    Warfile: 'C:\myagent\vsts-agent-win-x64-3.236.1\_work\7\s\target'
    Context: '/deploy'
    ServerVersion: '7OrAbove'

